// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipncjsbjvdepjsowdhkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbmNqc2JqdmRlcGpzb3dkaGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTI3NjgsImV4cCI6MjA2MDk4ODc2OH0.p9jyxC5nca7XIGtle7jQeW6flkK1R7y-M-uaifZ6d2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);